apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-resources
spec:
  validationFailureAction: enforce
  background: true
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: validate-resources
      match:
        any:
        - resources:
            kinds:
              - ClusterRole
              - ClusterRoleBinding
              - ConfigMap
              - Deployment
              - Pod
              - Role
              - RoleBinding
              - Secret
              - Service
              - ServiceAccount
              - ClusterPolicy
              - Policy
            name: test*
      # ExcludeResources defines when this policy rule should not be applied.
      exclude:
        any:
        - resources:
            kinds:
              - Pod
          subjects:
          - kind: ServiceAccount
            namespace: kube-system
            name: replicaset-controller
        - resources:
            kinds:
              - ReplicaSet
          subjects:
          - kind: ServiceAccount
            namespace: kube-system
            name: deployment-controller
        - resources:
            kinds:
              - Secret
          subjects:
          - kind: User
            name: system:kube-controller-manager
      validate:
        manifests:
          attestors:
          - entries:
            - keys: 
                publicKeys:  |-
                  -----BEGIN PUBLIC KEY-----
                  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyQfmL5YwHbn9xrrgG3vgbU0KJxMY
                  BibYLJ5L4VSMvGxeMLnBGdM48w5IE//6idUPj3rscigFdHs7GDMH4LLAng==
                  -----END PUBLIC KEY-----
          ignoreFields:
          - objects:
            - kind: Deployment
            fields:
            - spec.replicas
          - objects:
            - kind: ClusterPolicy
            - kind: Policy
            fields:
            - spec.rules.1.*
            - spec.rules.2.*